In [1]:
import numpy as np

In [15]:
a = np.random.rand(3,3)
b = np.random.rand(a.shape[0], a.shape[1])
print(a)

[[0.16472438 0.65808318 0.62530328]
 [0.61015799 0.42732649 0.35132078]
 [0.88764151 0.03371855 0.57506829]]
