In [8]:
import numpy as np

In [9]:
a = np.arange(9.0).reshape(3,3)
b = np.arange(3.0)
print(a)
print(b)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[0. 1. 2.]


In [10]:
print(np.divide(a, b))

[[nan 1.  1. ]
 [inf 4.  2.5]
 [inf 7.  4. ]]


C:\Users\mings\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\mings\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [12]:
a = np.array((1, 0, 0))
b = a
dA2 = - (np.divide(a, b) - np.divide(a, b))
print(dA2)

[-0. nan nan]


C:\Users\mings\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
